services:
  app:
    restart: always
    image: ubuntu:22.04
    build:
      context: .
    environment:
      - PGUSER=${POSTGRES_USER_NAME}
      - PGPASSWORD=${POSTGRES_USER_PASSWORD}
      - PGDATABASE=${POSTGRES_USER_DATABASE_NAME}
      - PGPORT=5432
      - PGHOST=postgres
    env_file:
      - .env
    ports:
      - "0.0.0.0:7777:7777"
    depends_on:
      - postgres
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 2m


  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PROJECT_USER_NAME: ${POSTGRES_USER_NAME}
      PROJECT_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
      PROJECT_USER_DATABASE_NAME: ${POSTGRES_USER_DATABASE_NAME}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env