#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$POSTGRES_USER_NAME" WITH PASSWORD '$POSTGRES_USER_PASSWORD' LOGIN;
    CREATE DATABASE "$POSTGRES_USER_DATABASE_NAME" OWNER "$POSTGRES_USER_NAME";
    GRANT ALL ON SCHEMA public TO "$POSTGRES_USER_NAME";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$POSTGRES_USER_NAME";
EOSQL

PGPASSWORD="${POSTGRES_USER_PASSWORD}" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_NAME" --dbname "$POSTGRES_USER_DATABASE_NAME" -f /docker-entrypoint-initdb.d/init.sql <<-EOSQL
EOSQL