name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake
      - name: build
      run: mkdir -p build && cd build && cmake .. && make
      - name: Smoke test server
      run: ./http-server
      if: ${{ wget --timeout=5 --tries=1 --spider http://localhost:7777/ }}
      run: pkill http-server
      - name: Smoke test client
      run: ./http-client
      run: pkill http-client