name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake wget
      
      - name: Build
        run: mkdir -p build && cd build && cmake .. && make
      
      - name: Start server
        run: ./build/http-server &
      
      - name: Smoke test server
        shell: bash
        run: |
          if ! wget --timeout=5 --tries=1 --spider http://localhost:7777/; then
            exit 1
          fi
      
      - name: Smoke test client
        run: ./build/http-client &
      
      - run: pkill http-server
      - run: pkill http-client